services:
  suitefishdev:
    build: .
    image: bugfishtm/suitefishdev:latest
    restart: always
    volumes:
      - sys-ssl:/opt/sf_ssl
      - sys-mysql:/var/lib/mysql
      - ./_source:/var/www/html
    ports:
      - 80:80
      - 443:443
    environment:
      sf_db_pass:       "${sf_db_pass}"
      sf_url:           "${sf_url}"
      sf_timezone:      "${sf_timezone}"
volumes:
  sys-mysql:
  sys-ssl: