services:
  sf-base:
    build: .
    image: bugfishtm/sf-base:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      sf_db_pass:       "${sf_db_pass}"
      sf_url:           "${sf_url}"
      sf_timezone:      "${sf_timezone}"