site_name: Suitefish CMS
repo_url: https://github.com/bugfishtm/suitefish-cms
repo_name: suitefish-cms

nav:
    - Introduction: index.md
    - Screenshots: screenshots.md
    - Tutorials: tutorials.md
    - Download: download.md
    - Installation: installation.md
    - Core Documentation:        
        - Functions: ./developer/corelib.md
        - Folders: ./developer/folders.md
        - 3rd Party: ./developer/vendor.md 
    - Modules Documentation:       
        - Site Module: ./developer/mod-site.md
        - Extension Module: ./developer/mod-ext.md
        - Image Module: ./developer/mod-image.md
        - Software Module: ./developer/mod-software.md
        - Docker Module: ./developer/mod-docker.md
        - Theme Module: ./developer/mod-theme.md
    - Support: support.md
    - License: license.md
    - Impressum: https://bugfishtm.blogspot.com/2023/05/impressum.html
    - Privacy: https://bugfishtm.blogspot.com/2023/05/privacy.html
    - More by Bugfish: https://bugfishtm.github.io

theme:
  name: material
  logo: ./logo.png
  favicon: ./favicon.ico
  primary: deep orange
  language: 'en'
  accent: deep orange
  font: false
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
    - mkdocstrings
    - search
    - mkdocs-video
    - glightbox
    
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
use_directory_urls: false

extra:
  meta:
    author: "Jan-Maurice Dahlmanns"