site_name: Suitefish CMS
repo_url: https://github.com/bugfishtm/suitefish-cms
repo_name: suitefish-cms

nav:
    - Overview: index.md
    - Screenshots: screenshots.md
    - Tutorials: tutorials.md
    - Download: download.md
    - Installation: installation.md
    - Functions: ./developer/corelib.md
    - Folders: ./developer/folders.md
    - Site Modules: ./developer/mod-site.md
    - Extension Modules: ./developer/mod-ext.md
    - Image Modules: ./developer/mod-image.md
    - Software Modules: ./developer/mod-software.md
    - Docker Modules: ./developer/mod-docker.md
    - Theme Modules: ./developer/mod-theme.md
    - Libraries: ./developer/vendor.md 
    - Contributing: contributing.md
    - Warranty: warranty.md
    - Support: support.md
    - License: license.md
    - Impressum: https://bugfishtm.blogspot.com/2023/05/impressum.html
    - Privacy: https://bugfishtm.blogspot.com/2023/05/privacy.html

theme:
  name: material
  logo: ./logo.png
  favicon: ./favicon.ico
  primary: deep orange
  language: 'en'
  accent: deep orange
  font: false
  features:
    - content.code.copy
  palette:
    - scheme: slate
      primary: deep orange
      accent: deep orange

extra_css:
  - extra.css

extra_javascript:
  - extra.js

plugins:
    - mkdocstrings
    - search
    - mkdocs-video
    - glightbox
    
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
use_directory_urls: false

extra:
  meta:
    author: "Jan-Maurice Dahlmanns"